### PR TITLE
aoesu rename

### PR DESCRIPTION
**Pull request by Beyley**
Closes part of #1

### CODE REVIEW

**Review by Eeveelution — APPROVED** [review]

**Comment by Eeveelution** [comment]
though it doesnt fix the part that its coded in c

**Comment by PoltixeTheDerg** [comment]
that can be done later, but this fixes at least one part

**Comment by aoeu1** [comment]
this is bullying help

**Comment by PoltixeTheDerg** [comment]
deal with it

**Comment by Eeveelution** [comment]
get fucked kekw

**Comment by Eeveelution** [comment]
get fucked kekw

**Comment by Beyley** [comment]
can i watch that

**Comment by Eeveelution** [comment]
> can i watch that

die

**Comment by Beyley** [comment]
I've tried dude

**Comment by aoeu1** [comment]
i tried compiling this and it brokee my pc bad patch sorry

**Pull request closed without merging**
